services/main/.gitignore, services/main/Domains/Auth/README.md, services/main/Domains/CollectionMngmt/README.md, services/main/Domains/IndexContent/README.md, services/main/Domains/SearchContent/README.md, services/main/Makefile, services/main/Models/Admin.cs, services/main/Models/Collection.cs, services/main/Models/CollectionContent.cs, services/main/Models/Content.cs, services/main/Models/CreatorApplication.cs, services/main/Models/RekognitionMetaData.cs, services/main/Models/S3MetaData.cs, services/main/Models/Tag.cs, services/main/Models/User.cs, services/main/Program.cs, services/main/Properties/launchSettings.json, services/main/README.md, services/main/main.csproj
=> Add Models

services/main/Controllers/Media.cs, services/main/DTOs/OutputContent.cs, services/main/Domains/IndexContent/IndexContentService.cs, services/main/Domains/IndexContent/ProcessIndexContentService.cs, services/main/Domains/SearchContent/SearchContentService.cs, services/main/Models/Content.cs, services/main/Program.cs, services/main/Transformations/GetOutputContent.cs
=> feat: Visual Search

apps/client/app/components/layout/header/index.tsx, apps/client/app/hooks/use-scroll.ts, apps/client/app/modules/index.tsx, apps/client/app/modules/policy/index.tsx, apps/client/app/modules/terms/index.tsx, apps/client/app/routes/privacy.ts, apps/client/app/routes/terms.ts
=> Policy & Terms of use layout

apps/client/app/modules/404-page/index.tsx, apps/client/app/modules/auth/login/context/index.tsx, apps/client/app/modules/auth/login/facebook/index.tsx, apps/client/app/modules/auth/login/google/index.tsx, apps/client/app/modules/auth/login/index.tsx, apps/client/app/modules/auth/login/twitter/index.tsx, apps/client/app/modules/landing-page/components/hero-section/index.tsx, apps/client/app/providers/auth/index.tsx, apps/client/app/root.tsx
=> Invalidate query when user's logged out

.gitignore, apps/client/app/components/layout/header/index.tsx, apps/client/package.json, apps/client/yarn.lock
@Bendomey removed husky for now, i would configure properly
=> Fixed mobile redirect for sign in

apps/client/app/components/Content/index.tsx, apps/client/app/components/creator-card/index.tsx, apps/client/app/components/flyout/flyout-container.tsx, apps/client/app/components/tooltip/tooltip-container.tsx, apps/client/app/hooks/use-boolean.ts, apps/client/app/modules/landing-page/index.tsx
=> Added flyout component for creator brief info on card hover

apps/client/app/modules/account/components/cover.tsx, apps/client/app/modules/account/tabs/about.tsx
=> Update: Redesigned creator page

apps/client/app/providers/auth/index.tsx, apps/client/server/dev.js
=> chore: fix reload issues

apps/client/app/components/layout/header/index.tsx, apps/client/app/modules/landing-page/components/pricing/index.tsx, apps/client/app/modules/landing-page/index.tsx
=> Add pricing component

apps/client/app/components/layout/header/search/visual/index.tsx
=> Added logic for image capture

services/main/Configurations/AppConstants.cs, services/main/Configurations/RabbitMQConnection.cs, services/main/Controllers/Media.cs, services/main/DTOs/OutputContent.cs, services/main/DTOs/OutputTag.cs, services/main/DTOs/OutputUser.cs, services/main/DTOs/SaveCollection.cs, services/main/DTOs/SaveCollectionContent.cs, services/main/DTOs/SaveMedia.cs, services/main/Domains/Auth/AuthService.cs, services/main/Domains/CollectionMngmt/CollectionContentService.cs, services/main/Domains/CollectionMngmt/CollectionService.cs, services/main/Domains/IndexContent/IndexContentService.cs, services/main/Domains/IndexContent/ProcessIndexContentService.cs, services/main/Lib/ProcessImage.cs, services/main/Models/Collection.cs, services/main/Models/CollectionContent.cs, services/main/Models/Content.cs, services/main/Models/ContentTag.cs, services/main/Models/CreatorApplication.cs, services/main/Models/RekognitionMetaData.cs, services/main/Models/Tag.cs, services/main/Models/User.cs, services/main/Program.cs, services/main/Transformations/GetOutputContent.cs, services/main/Transformations/GetOutputTag.cs, services/main/Transformations/GetOutputUser.cs, services/main/appsettings.json, services/main/main.csproj
=> Feat: Upload Contents

apps/client/app/components/animation/TypeWriteEffect.tsx, apps/client/app/components/creator-card/index.tsx, apps/client/app/modules/auth/login/index.tsx, apps/client/app/modules/auth/onboarding/index.tsx, apps/client/app/modules/landing-page/components/hero-section/index.tsx
PS: Don't mind me, it's just me experimenting but it's pretty cool ahaha
=> chore: added ui enhancements to auth flow

apps/wait-list/app/components/image-slider/index.jsx, apps/wait-list/app/components/layout/container.tsx, apps/wait-list/app/components/layout/header.tsx, apps/wait-list/app/components/layout/index.ts, apps/wait-list/app/components/moving-border/index.tsx, apps/wait-list/app/lib/cn.ts, apps/wait-list/app/modules/landing-page/index.tsx, apps/wait-list/package.json, apps/wait-list/tailwind.config.ts, apps/wait-list/tsconfig.json, apps/wait-list/types/global.d.ts
=> Feat - Added landing page for waitlist 

apps/wait-list/app/components/spring-modal/index.tsx, apps/wait-list/app/modules/landing-page/components/account-type.tsx, apps/wait-list/app/modules/landing-page/index.tsx, apps/wait-list/app/modules/landing-page/modals/wait-list-form/index.tsx, apps/wait-list/types/user.d.ts
=> Added wait-list form

apps/wait-list/app/components/animated-tooltip/index.tsx, apps/wait-list/app/components/layout/container.tsx, apps/wait-list/app/components/layout/header.tsx, apps/wait-list/app/modules/index.ts, apps/wait-list/app/modules/learn-more/index.tsx, apps/wait-list/app/routes/learn-more.ts
=> added learn more page to wait list

apps/wait-list/app/components/layout/header.tsx, apps/wait-list/app/components/svgs/twitter.tsx, apps/wait-list/app/modules/landing-page/modals/wait-list-form/index.tsx
=> Added waitlist success and twitter feed page

apps/client/app/components/footer/index.tsx, apps/client/app/constants/index.ts, apps/client/app/modules/explore/index.tsx, apps/client/app/modules/landing-page/index.tsx, apps/client/app/modules/policy/index.tsx, apps/client/app/modules/terms/index.tsx, apps/wait-list/app/modules/landing-page/components/account-type.tsx
=> Added footer on client app

services/main/Controllers/Admin.cs, services/main/Controllers/Auth.cs, services/main/DTOs/AuthenticateInput.cs, services/main/DTOs/SetupAccountInput.cs, services/main/Domains/AdminMngmt/SearchAdminService.cs, services/main/Domains/AdminMngmt/dto.cs, services/main/Domains/UserMngmt/CreatorApplicationService.cs, services/main/Domains/UserMngmt/UserService.cs, services/main/Domains/UserMngmt/dto.cs, services/main/Transformations/GetOutputUser.cs, services/main/Transformations/UserTransformer.cs
This pull request contains the endpoints for getting creator applications and users by the admin with the appropriate filters
=> feat:: get users, get creator-applications

apps/admin/TestData.ts, apps/admin/app/creator-applications/page.tsx, apps/admin/components/LoadingContainer/index.tsx, apps/admin/components/table/index.tsx, apps/admin/components/ui/checkbox.tsx, apps/admin/components/ui/input.tsx, apps/admin/components/ui/scroll-area.tsx, apps/admin/components/ui/select.tsx, apps/admin/components/ui/table.tsx, apps/admin/modules/application/index.tsx, apps/admin/modules/index.ts, apps/admin/package.json, apps/admin/tailwind.config.ts, apps/admin/types/README.md, apps/admin/types/application/index.ts, apps/admin/types/misc/index.d.ts, apps/admin/yarn.lock
=> [Admin] - Gab/list applications

apps/admin/app/layout.tsx, apps/admin/components/ModeToggle/index.tsx, apps/admin/components/Theme-provider/index.tsx, apps/admin/components/header.tsx, apps/admin/components/index.ts, apps/admin/modules/application/index.tsx, apps/admin/modules/application/reject/index.tsx, apps/admin/package.json, apps/admin/yarn.lock
=> [Admin ] - gab/reject-application

services/main/Controllers/Wallet.cs, services/main/DTOs/OutputWallet.cs
=> feat: Admin endpoint for wallet transaction

services/main/Controllers/Content.cs, services/main/DTOs/Content.cs, services/main/Domains/Content/EditContentService.cs, services/main/Domains/Content/IndexContentService.cs, services/main/Domains/Content/PermissionService.cs, services/main/Domains/Content/dto.cs, services/main/Lib/Money.cs, services/main/Middlewares/E2ECacheLayer.cs, services/main/Program.cs
feat: Edit Content Details
Register an endpoint to update contents on FE
- Endpoint: `PATCH /api/v1/contents/{contentId}`
- Body: 
```
{
title?: string
visibility?: "PUBLIC" | "PRIVATE"
amount?: number
}
```
- Authorisation: Needs Token
> You should only pass the keys you really want to update. Don't pass all the values to improve the efficiency of that endpoint because each key has some checks done on them before the update is successfully completed
- Login
- Create a content
- Call the edit endpoint to update any detail
- Verify by looking at the response  from the api call or by calling the get endpoint(`GET /api/v1/content/{contentId}`) with the same content Id
N/A
N/A
=> feat: [API] Edit Content Details

apps/client/app/api/contents/index.ts, apps/client/app/modules/collections/single/index.tsx, apps/client/app/modules/photo/components/related-content.tsx, apps/client/app/modules/photo/index.tsx, services/main/Controllers/Content.cs, services/main/Domains/Content/SearchContentService.cs
Related Images for a Content
User should be able to see related images when they view a single image content
- "The definition of image relation": Contents that have similar tags.
Select an image. If we have contents with similar tags, they should appear beneath it.
N/A
N/A
=> feat: Related Images for a Content

apps/admin/api/content/index.ts, apps/admin/modules/content/feature/index.tsx, apps/admin/modules/content/index.tsx
Set content as featured
Created a modal to mark content as featured
N/A
N/A
=> [Admin Portal ] - Gab/feature content

apps/admin/api/content/index.ts, apps/admin/modules/content/index.tsx, apps/admin/modules/content/unfeature/index.tsx
Unfeature content
Added unfeature modal
N/A
N/A
=> [Admin ] - Gab/unfeature content

services/main/Controllers/Collection.cs, services/main/Controllers/Tag.cs, services/main/DTOs/OutputCollection.cs, services/main/Domains/Collection/CollectionContentService.cs, services/main/Domains/Collection/CollectionService.cs, services/main/Transformations/CollectionTransformer.cs
Feature/Hide Collections
Helps us feature/unfeature collections
```
- PATCH /collections/{id}/feature
- PATCH /collections/{id}/feature
```
> isFeatured field is added to collections models
- After featuring a collection, collections's `isFeatured` field should be true.
N/A
N/A
=> feat: Feature/hide collections

apps/admin/api/tag/index.ts, apps/admin/modules/tag/feature/index.tsx, apps/admin/modules/tag/index.tsx, apps/admin/types/tag/index.ts
Feature tag
Added feature tag modal
N/A
N/A
=> [Admin ] - Gab/feature tag

apps/admin/api/tag/index.ts, apps/admin/modules/tag/index.tsx, apps/admin/modules/tag/unfeature/index.tsx
Unfeature Tag
Added unfeature modal
N/A
N/A
=> [Admin ] - Gab/unfeature tag

apps/client/app/modules/photo/index.tsx, apps/client/app/modules/search/components/filters-dialog/index.tsx, apps/client/app/modules/search/components/license-select/index.tsx, apps/client/app/modules/search/components/orientation-select/index.tsx, apps/client/app/modules/search/index.tsx, apps/client/types/collection.d.ts, apps/client/types/content.d.ts, apps/client/types/tag.d.ts, services/main/Controllers/Collection.cs, services/main/Domains/Collection/CollectionService.cs, services/main/Domains/Collection/dto.cs, services/main/Domains/Content/IndexContentService.cs
Search Filters
Worked on the search filters
On smaller screens, we invoke dialog to see the different filter options
Visit the `/search/photos/search-query` page to see 
N/A
N/A
=> chore: Search Filters

apps/client/app/constants/index.ts, apps/client/app/modules/landing-page/index.tsx, apps/client/app/routes/_index.ts, apps/client/types/content.d.ts, services/main/Controllers/Content.cs, services/main/Domains/Content/SearchContentService.cs, services/main/Domains/Content/dto.cs
Fetch contents on homepage
Fetch paginated content
Changed homepage file
Visit the homepage
N/A
N/A
=> feat: Fetch contents on homepage

apps/admin/api/collection/index.ts, apps/admin/api/content/index.ts, apps/admin/modules/admin/index.tsx, apps/admin/modules/collection/index.tsx, apps/admin/modules/collection/unfeature/index.tsx, apps/admin/modules/content/index.tsx, apps/admin/modules/creator-application/index.tsx, apps/admin/modules/tag/index.tsx, apps/admin/modules/user/index.tsx, apps/admin/modules/wallet-transaction/index.tsx, apps/admin/types/content/index.ts
Unfeature Collection
- Added unfeature collection modal
- Changed default page number to zero
- Changed Content api
N/A
N/A
=> [Admin ] - Gab/unfeature collection

apps/client/app/components/Content/index.tsx, apps/client/app/modules/account/home/components/other-creators.tsx, apps/client/app/modules/explore/components/section/content-section.tsx, apps/client/app/modules/photo/components/edit-title-modal/index.tsx, apps/client/types/content.d.ts
fix explore mfoni content size
fix explore mfoni content size
Go to explore page
N/A
N/A
=> chore: fix explore mfoni content size

apps/client/app/api/contents/index.ts, apps/client/app/modules/photo/components/edit-title-modal/index.tsx, apps/client/app/modules/photo/index.tsx, apps/client/app/routes/api.update-content.ts
Edit Content
Content owner should be able to update content
Using server components to update content so that any content that is server side rendered will also get updated
- Upload content
- view single content
- click on pencil icon near the content name to update
N/A
N/A
=> feat: edit content

apps/client/app/api/collections/index.ts, apps/client/app/modules/explore/collections/single/components/edit-collection-modal/index.tsx, apps/client/app/modules/explore/collections/single/index.tsx, apps/client/app/modules/photo/components/edit-title-modal/index.tsx, apps/client/app/routes/api.update-collection.ts
Edit collection title
Collection owner should be able to update collection
Using server components to update collection so that any content that is server side rendered will also get updated
- Create collection
- view single collection
- click on more menu and "edit title" menu item
N/A
N/A
=> feat: edit collection title

apps/client/app/modules/explore/collections/single/components/remove-image-content-dialog.tsx, apps/client/app/modules/explore/collections/single/components/status-button.tsx, apps/client/app/modules/explore/collections/single/index.tsx, services/main/Domains/Collection/CollectionContentService.cs
hide/publish collections
Users should be able to hide/publish collections
- Create a new collection
- Add contents to collection
- publish button should become active
N/A
N/A
=> feat: hide/publish collections

apps/admin/lib/format-amount.ts, apps/admin/lib/index.ts, apps/admin/modules/content/index.tsx, apps/admin/modules/wallet-transaction/components/wallet.tsx, apps/admin/modules/wallet-transaction/index.tsx
Convert currency
format-amount, wallet.tsx, wallet-transaction
N/A
N/A
=> [Admin ] - Format Currency

apps/client/app/api/contents/index.ts, apps/client/app/api/creators/index.ts, apps/client/app/lib/misc.ts, apps/client/app/modules/account/creator/index.tsx, apps/client/app/modules/search/collections/index.tsx, apps/client/app/modules/search/creators/index.tsx, apps/client/app/modules/search/photos/index.tsx, apps/client/app/routes/$username.ts, apps/client/app/routes/explore.contents.ts, apps/client/app/routes/search.collections.$query.ts, apps/client/app/routes/search.creators.$query.ts, apps/client/app/routes/search.photos.$query.ts, services/main/Controllers/Creator.cs, services/main/Domains/User/CreatorService.cs, services/main/Domains/User/dto.cs
Search integration on app
Search integration with API
- Create new endpoint for search creators
- Integrate with photos api for search
- Integrate with collections api for search
- Visit app
- Click on the search bar
- type anything and press enter
- you should get results from photos, collections and creators
N/A
N/A
=> feat: Search integration on app

services/main/Controllers/Content.cs, services/main/DTOs/Content.cs, services/main/Domains/Content/DownloadContentService.cs, services/main/Domains/Content/dto.cs, services/main/Models/ContentDownload.cs, services/main/Program.cs
feat: Register an endpoint for getting media from content
Register an endpoint for getting media from content
- Added a new handler in the content controller to retrieve content
- Added a new service for downloading content
Make a request to the endpoint.
N/A
N/A
=> feat: Register an endpoint for getting media from content

apps/client/app/api/contents/index.ts, apps/client/app/api/image/index.ts, apps/client/app/components/Content/index.tsx, apps/client/app/components/download-button.tsx, apps/client/app/modules/photo/index.tsx, apps/client/app/routes/api.download-content.ts, apps/client/server/routes/s3.ts, apps/client/types/content.d.ts
feat: Download Content FE integration
Download Content FE integration
Added api functions to request for a temporal download link via s3 
Click on the download button on any content
N/A
N/A
=> feat: Download Content FE integration

apps/client/app/routes/api.download-content.ts, apps/client/server/routes/s3.ts
Download fails when there're spaces in the key.
=> fix image download

apps/client/app/components/flyout/flyout-container.tsx, apps/client/app/components/layout/header/index.tsx, apps/client/app/components/layout/header/search/index.tsx, apps/client/app/components/system-alerts/index.tsx, apps/client/app/components/system-alerts/use-system-alert-handler.ts, apps/client/app/lib/bypass-cf-asset-worker.ts, apps/client/app/modules/auth/login/index.tsx, apps/client/app/modules/landing-page/components/hero-section/index.tsx, apps/client/app/modules/photo/index.tsx, apps/client/app/routes/$username.ts, apps/client/app/routes/explore.collections.$collection.ts, apps/client/app/routes/photos.$slug.ts, apps/client/app/styles/tailwind.css
First time users will see this. just to guide them.
=> Tour: Helpful text for visual search
